### ISSUE TITLE
Make a deny_unencrypted_efs_actions

### ISSUE THREAD

**Issue by KevinHock** [ScaleSec/terraform_aws_scp#55]
Just like
https://github.com/ScaleSec/terraform_aws_scp/blob/main/security_controls_scp/modules/rds/deny_unencrypted_actions.tf
but instead of RDS

you can maybe do EFS, similar to as shown here:
https://docs.aws.amazon.com/efs/latest/ug/using-iam-to-enforce-encryption-at-rest.html

**Comment by jdyke** [comment]
Great idea @KevinHock! We will look into what's available as far as condition logic and get back to you.

**Comment by KevinHock** [comment]
Seems like the condition keys do indeed exist https://docs.aws.amazon.com/efs/latest/ug/using-iam-to-enforce-encryption-at-rest.html

Just can't find that nice table that lists all the condition keys, for EFS, like I normally can for e.g. Ec2 🤔

**Comment by jdyke** [comment]
Hey @KevinHock thanks for the info. We have a branch currently awaiting final testing by @JohnDavisPorter that will be merged once the PR is opened.

https://github.com/ScaleSec/terraform_aws_scp/commit/f6b8b7b268b3ebbccebe89a42cf9d530670bfb38

**Comment by jdyke** [comment]
Closed via #73
