### ISSUE TITLE
Preventing AMIs from becoming public

### ISSUE THREAD

**Issue by KevinHock** [ScaleSec/terraform_aws_scp#57]
I know that https://github.com/ScaleSec/terraform_aws_scp/blob/main/security_controls_scp/modules/ec2/deny_public_ami.tf "Denies users the ability to launch EC2 instances with public AMIs.", but perhaps it's possible to stop it before it is made public.

`ModifyImageAttribute` is the action, ` --launch-permission "Add=[{Group=all}]"` seems to be the condition.

https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-image-attribute.html#examples

**Comment by jdyke** [comment]
ModifyImageAttribute does not support condition keys at this time

![image](https://user-images.githubusercontent.com/19151605/101176740-e68a4800-3614-11eb-869c-6ba79096212a.png)

**Comment by KevinHock** [comment]
Thank you @jdyke ! ❤️
