### ISSUE TITLE
Prevent RDS snapshots from becoming public

### ISSUE THREAD

**Issue by KevinHock** [ScaleSec/terraform_aws_scp#58]
At least encryption makes this never an issue, but for completeness, [`ModifyDBSnapshotAttribute`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBSnapshotAttribute.html) and [`ModifyDBClusterSnapshotAttribute`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBClusterSnapshotAttribute.html) can make an RDS snapshot public. These were the only `rds:` action I saw that could do this, but I could be wrong.

Making it public would have a `ValuesToAdd` set to `all`.

**Comment by cleibl** [comment]
same as #59 - There is no [RDS condition](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonrds.html#amazonrds-policy-keys) which would allow us to ensure the DB snapshots are not public via an SCP.

Closing issue

**Comment by KevinHock** [comment]
++, thanks for looking at this! _sad trombone_
