### ISSUE TITLE
Compliance policies should pull from AWS-allowlist

### ISSUE THREAD

**Issue by danquack** [ScaleSec/terraform_aws_scp#74]
In https://github.com/salesforce/aws-allowlister/issues/74 we discussed referencing the json policies from aws-allowlister. Since they policies are updated frequently under https://github.com/salesforce/aws-allowlister/tree/main/examples/latest, it may make sense to use an http data source, or have a scheduled job that pulls down the policies from https://raw.githubusercontent.com/salesforce/aws-allowlister/main/examples/latest/x.json. 

CC @jdyke let me know if you think this needs different wording, or if I interpreted your comments incorrectly

**Comment by jdyke** [comment]
This makes perfect sense, thanks for creating the issue!

**Comment by jdyke** [comment]
I'm going to take a look at this today.
